var GAME_LEVELS = [
  ["                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                xxxx",
   "                                                                               xxxxx",
   "                                                                              xxxxxx",
   "                                                                             xxxxxxx",
   "                                                                             xxxxxxx",
   "                                                                             xxxxxxx",
   "  y  @                                            xxxxxxxx                  oxxxxxxx",
   "xxxxxxx                                            x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   xx                                           x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x x                                          x     xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x  x                                        x        xxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x   x                                       x          xxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x   xx                                      x            xxxxxxxxxxxxxxxxxxxxx",
   "  x   x   x x                                   xxx              xxxxxxxxxxxxxxxxxxx",
   "  x   x   x  x                                  x x                xxxxxxxxxxxxxxxxx",
   "  x   x   x   x                 xxx             x x                  xxxxxxxxxxxxxxx",
   "  x   x   x    xxxx  xxxxxx     x x w xxxx      x x                    xxxxxxxxxxxxx",
   "  x   x   x    x  x  x    x     x  xxx   x      x x                      xxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                            x                                   x                                          ",
   "                                                            x                                   x                                          ",
   "                                                            x                                   x                                          ",
   "                                                            x                                   x                                          ",
   "                                                            x                                   x                                          ",
   "                                                            x                                   x                                          ",
   "                                                            x            z                      x                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxx  xxx  xxx  xxx                                          ",
   "                                                                                 x  x x  x x  x x                                          ",
   "                                        |     |     |               x            x  x x  x x  x x                                          ",
   "                                 v%                                x             x  x x  x x  x x                                          ",
   "                                                                  x              x  x x  x x  x x                                          ",
   "                                                                                 x  x x  x x  x x                                          ",
   "                                                              xx                 x  x x  x x  x x                                          ",
   "                          xxxxxxxxxxxxxxxxxxxxxxx            x                   x  x x  x x  x x                                          ",
   "                         x                       xxxxxxxxxxxx                    x  x x  x x  x x                                          ",
   "                        x                                                        x  x x  x x  x x                                          ",
   "                       x                                                         x  x x  x x  x x                                          ",
   "                                                                                 x  x x  x x  x x                                          ",
   "                   p                                                             x  x x  x x  x x                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxx    xxxx                                        xxxx      x  x x  x x  x x                                          ",
   "x                         x    x                              v%      x    x     x  x x  x x  x x                     xxxxxxx              ",
   "x                        x  x   x                                    x  x   x    x  x x  x x  x x                 xxxx    |  xx            ",
   "x                        xxx    x                                    xxx    x    x  x x  x x  x x              xxx            xxx          ",
   "x                         vx   x        xxx                           vx   x     x  x x  x x  x x           xxx      v   v       xxx       ",
   "x                          xxxx        x   x                           xxxx      x  x x  x x  x x         xx      |        v    v   x      ",
   "x                                    xx    xx                                    x  x x  x xp x x   xxxxxx               |      v   xx     ",
   "x      @                            x  x  x  x                                   x  x x  x x  x xxxx                                 xx    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x x  x x  x x                                   xxx    ",
   "                                                                                x 0 x x  x x  x         |   |   |                    xx    ",
   "                                                                               x 0 x  x  x x  x                                       x    ",
   "                                                                              x 0 x   x  x x  x                                       x    ",
   "                                                                             x 0 x    x  x x  x                                       x    ",
   "                                                                            x 0 x     x  x x  x                                       x    ",
   "                                                                           x 0 x      x  x x                                          x    ",
   "                                                                          x 0 x       x  x x                                          x    ",
   "                                                                         x 0 x        x  x x                                          x    ",
   "                                                                        x 0 x         x  x x                                          x    ",
   "       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 0 x          x  x x                                          x    ",
   "                                           x00000000000000000000000000000 x           x  x x                                          x    ",
   "                                         xxx00000000000000000000000000000x            x  x x p                                        x    ",
   "                                         x000000000000000000000000000000x             x  x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                                         x00000000000000000000000000000x              x  x                                                 ",
   "                                         x00xxxxxxxxxxxxxxxxxxxxxxxxxxx               x  x                                                 ",
   "                                          00                                          x  x                                                 ",
   "                                          00                                          x  x                                                 ",
   "                                          00                                          x  x                                                 ",
   "                                                                                      x  x                                                 ",
   "                                                                          xxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                          x        q            x      q      x                        x   ",
   "                                                                          x        q            q      q      q                        x   ",
   "                                                                          x        x        ^   q      x      q                        x   ",
   "                                                                          xxxxqqqxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqqqx   ",
   "                                                                          x                                          x         q       x   ",
   "                                                                          x                                          q        q q      x   ",
   "                                                                          x                                          q        qoq      x   ",
   "                                                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                                                                                           "],
  ["                                                                                                                                      ",
   "                                                                                                                                      ",
   "                                                                                                                                      ",
   "                                                                                                                                      ",
   "                                                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                             xxxxxxxxx                                               x",
   "                                                                             xxxxxxxxx    =                                          x",
   "                                                                             xx                                                      x",
   "                                                   xxxxxxxx                  xxo                       =                             x",
   "xxxxxxx                                            x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqqqqx",
   "  x   xx                                           x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxx             |           |                       x",
   "  x   x x                                          x     xxxxxxxxxxxxxxxxxxxxxxxxxxx    |                                           xx",
   "  x   x  x                                        x        xxxxxxxxxxxxxxxxxxxxxxxxx                                  |            xxx",
   "  x   x   x                                       x          xxxxxxxxxxxxxxxxxxxxxxx                                              xxxx",
   "  x   x   xx                                      x            xxxxxxxxxxxxxxxxxxxxxqqqxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x   x x                                   xxx              xxxxxxxxxxxxxxxxxxxx     =                   =                      x",
   "  x   x   x  x                                  x x                xxxxxxxxxxxxxxxxxxx=           =                                  x",
   "  x   x   x   x                 xxx             x x                  xxxxxxxxxxxxxxxxxx                                              x",
   "  x   x   x    xxxx  xxxxxx     x x w xxxx      x x                    xxxxxxxxxxxxxxxxx                           =               @ x",
   "  x   x   x    x  x  x    x     x  xxx   x      x x                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                                      ",
   "                                                                                                                                      "],
  ["                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                xxxx",
   "                                                                               xxxxx",
   "                                                                              xxxxxx",
   "                                                                             xxxxxxx",
   "                                                                             xxxxxxx",
   "                                                                             xxxxxxx",
   "   &                                               xxxxxxxx                @ xxxxxxx",
   "xxxxxxx                                            x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   xx                                           x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x x                                          x     xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x  x                                        x        xxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x   x                                       x          xxxxxxxxxxxxxxxxxxxxxxx",
   "  x   x   xx                                      x            xxxxxxxxxxxxxxxxxxxxx",
   "  x   x   x x                                   xxx              xxxxxxxxxxxxxxxxxxx",
   "  x   x   x  x                                  x x                xxxxxxxxxxxxxxxxx",
   "  x   x   x   x                 xxx             x x                  xxxxxxxxxxxxxxx",
   "  x   x   x    xxxx  xxxxxx     x x w xxxx      x x                    xxxxxxxxxxxxx",
   "  x   x   x    x  x  x    x     x  xxx   x      x x                      xxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
